FakeCSV/urls.py
from django.contrib import admin
from django.urls import include, path
from schemas.views import register_user


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register_user, name='register'),
    path('', include('schemas.urls')),
]

schemas/urls.py
from django.urls import path

from . import views


app_name = 'schemas'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/schema/', views.CreateSchemaView.as_view(), name='create_schema'),
    path('new/column/', views.ColumnCreateView.as_view(), name='create_column'),
    path('column/delete/<int:column_id>/', views.ColumnDeleteView.as_view(), name='delete_column'),
    path('schema/<int:schema_id>/', views.SchemaView.as_view(), name='schema_detail'),
    path('schema/delete/<int:schema_id>', views.DeleteSchemaView.as_view(), name='delete_schema'),
    path('schema/get_file/<int:dataset_id>/', views.FileDownloadView.as_view(), name='get_file'),
    path('tasks/<str:task_id>/', views.TaskStatusView.as_view(), name='task_status')
]

schemas/models.py
from django.db import models
from django.urls import reverse


class Schema(models.Model):
    """Represent schema model in database."""
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, null=True)
    modified = models.DateField(auto_now=True, null=True)
    confirmed = models.BooleanField(default=False)

    class Meta:
        ordering = ['pk']

    def get_absolute_url(self):
        return reverse('schemas:schema_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.name}'


class Column(models.Model):
    """Represent schema column in database."""
    COLUMN_TYPES = (
        ('Full name', 'Full name'),
        ('Color', 'Color'),
        ('City', 'City'),
        ('Company', 'Company'),
        ('Phone_number', 'Phone number'),
        ('Integer', 'Integer'),
        ('Country', 'Country'),
        ('Month', 'Month')
    )
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100, choices=COLUMN_TYPES)
    start = models.PositiveSmallIntegerField(null=True, blank=True)
    end = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.name} {self.type}'


class DataSet(models.Model):
    """Represent schema dataset in database."""
    STATUS = (
        ('Processing', 'Processing'),
        ('Ready', 'Ready')
    )
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, null=True)
    num_row = models.SmallIntegerField()
    status = models.CharField(max_length=50, default='Processing', choices=STATUS)
    created = models.DateField(auto_now_add=True, null=True)
    file = models.FileField(upload_to='data_sets/', null=True)

    def __str__(self):
        return f'{self.schema} - {self.num_row}'

schemas/forms.py
from django import forms
from .models import Schema, Column, DataSet


class SchemaCreateForm(forms.ModelForm):
    """Schema form."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control w-25'})
        self.fields['name'].label = 'Name'

    class Meta:
        model = Schema
        fields = ('name',)


class ColumnCreateForm(forms.ModelForm):
    """Column form."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Column
        fields = ('name', 'type', 'start', 'end')


class DataSetCreateForm(forms.ModelForm):
    """Dataset form."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['num_row'].widget.attrs.update({'class': 'form-control'})
        self.fields['num_row'].label = 'Rows:'

    class Meta:
        model = DataSet
        fields = ('num_row',)

schemas/views.py
from celery.result import AsyncResult
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import View

from .forms import ColumnCreateForm, DataSetCreateForm, SchemaCreateForm
from .models import Column, DataSet, Schema
from .tasks import form_fake_data


def register_user(request):
    """
    Display registation form, create new user and if success redirect to index page.
    """
    if request.method == "GET":
        return render(request, 'registration/register.html')

    elif request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('schemas:index'))


class IndexView(LoginRequiredMixin, View):
    """
    Responsible for index page. Display all user's schemas.
    """
    def get(self, request):
        schemas = Schema.objects.filter(confirmed=True, owner=request.user)
        return render(request, 'schemas/index.html', {'schemas': schemas})


class CreateSchemaView(LoginRequiredMixin, View):
    """
    Responsible for schema and columns creation page.
    Display forms and newly create columns.
    """
    def get(self, request):
        schema, _ = Schema.objects.get_or_create(owner=request.user, confirmed=False)
        columns = schema.column_set.all()
        form, col_form = SchemaCreateForm(instance=schema), ColumnCreateForm()
        context = {'schema': schema, 'columns': columns, 'form': form, 'col_form': col_form}
        return render(request, 'schemas/new_schema.html', context)

    def post(self, request):
        form = SchemaCreateForm(data=request.POST)

        if form.is_valid():
            schema = Schema.objects.get(owner=request.user, confirmed=False)
            schema.name = form.cleaned_data['name']
            schema.confirmed = True
            schema.save()
            return redirect(schema)


class ColumnCreateView(LoginRequiredMixin, View):
    """
    Responsible for column creation. Receive a POST AJAX request,
    create new column model in database and send json data to front end.
    """
    def post(self, request):
        if request.is_ajax():
            form = ColumnCreateForm(data=request.POST)

            if form.is_valid():
                column = form.save(commit=False)
                column.schema_id = request.POST.get('schema')
                column.save()
                response = {
                    'csrfmiddlewaretoken': request.POST.get('csrfmiddlewaretoken'),
                    'id': column.pk,
                    'name': column.name,
                    'type': column.type,
                    'start': column.start,
                    'end': column.end
                }
                return JsonResponse(response, status=202)

        else:
            return HttpResponseForbidden(status=403)


class ColumnDeleteView(LoginRequiredMixin, View):
    """
    Responsible for column removal. Receive a POST AJAX request,
    remove column from database and send json data to front end.
    """
    def post(self, request, column_id):
        if request.is_ajax():
            column = Column.objects.filter(id=column_id)
            column.delete()
            return JsonResponse({'success': column_id}, status=202)

        else:
            return HttpResponseForbidden(status=403)


class DeleteSchemaView(LoginRequiredMixin, View):
    """
    Responsible for delete schemas. Receive a POST AJAX request
    and delete schema in database and send json data to front end.
    """
    def post(self, request, schema_id):
        if request.is_ajax():
            schema = Schema.objects.filter(id=schema_id, owner=request.user)
            schema.delete()
            return JsonResponse({'succsess': schema_id}, status=200)


class SchemaView(LoginRequiredMixin, View):
    """
    Responsible for schema detail and related datasets page.
    Display datasets table and create dataset form.
    Receive a POST AJAX request, create new dataset model,
    start Celery task to form CSV file and send json data to front end.
    """
    def get(self, request, schema_id):
        schema = get_object_or_404(Schema, pk=schema_id, owner=request.user)
        data_sets = schema.dataset_set.all()
        form = DataSetCreateForm()
        context = {'schema': schema, 'data_sets': data_sets, 'form': form}
        return render(request, 'schemas/schema_detail.html', context)

    def post(self, request, schema_id):
        if request.is_ajax():
            schema = Schema.objects.get(id=schema_id, owner=request.user)
            form = DataSetCreateForm(data=request.POST)

            if form.is_valid():
                data_set = DataSet.objects.create(
                    schema_id=schema_id,
                    num_row=request.POST.get('num_row')
                )
                task = form_fake_data.delay(schema_id, data_set.id)

                response = {
                    'task_id': task.id,
                    'count': schema.dataset_set.count(),
                    'dataset_id': data_set.id,
                    'created': data_set.created,
                    'status': data_set.status
                }

                return JsonResponse(response, status=202)

        else:
            return HttpResponseForbidden(status=403)


class TaskStatusView(LoginRequiredMixin, View):
    """
    Realize Celery task status polling.
    Recieve a GET AJAX request, check task status and send json data to front end.
    """
    def get(self, request, task_id):
        if request.is_ajax():
            task_result = AsyncResult(task_id)
            result = {
                "task_id": task_id,
                "task_status": task_result.status
            }
            return JsonResponse(result, status=202)

        else:
            return HttpResponseForbidden(status=403)


class FileDownloadView(LoginRequiredMixin, View):
    """
    Response for downloading file.
    """
    def get(self, request, dataset_id):
        data_set = get_object_or_404(DataSet, id=dataset_id)
        return FileResponse(open(data_set.file.path, 'rb'))

schemas/templates/schemas/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home - FakeCSV{% endblock %}</title>
    <link rel="icon" href="{% static 'schemas/icon/favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'schemas/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'schemas:index' %}">Fake CSV</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
                <span class="navbar-text">
                    Hello, {{ user.username }}
                </span>
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'schemas/js/index.js' %}"></script>
</body>
</html>

schemas/templates/schemas/index.html
{% extends './base.html' %}


{% block content %}
<div class="mt-4">
    <h3 class="d-inline">Data Schemas</h3>
    <a class="btn btn-success d-inline float-end" href="{% url 'schemas:create_schema' %}" role="button">New schema</a>
</div>
<table class="table table-bordered text-center mt-5">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Modified</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for schema in schemas %}
            <tr>
                <th class="align-middle schemaCounter" scope="row">{{ forloop.counter }}</th>
                <td class="align-middle">{{ schema.name }}</td>
                <td class="align-middle">{{ schema.modified|date:"Y-m-d" }}</td>
                <td>
                    <a class="btn btn-primary mb-2 actionButton" href="{{ schema.get_absolute_url }}" role="button">Detail</a>
                    <form class="deleteSchema" action="{% url 'schemas:delete_schema' schema.pk %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger actionButton" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

schemas/templates/schemas/new_schema.html
{% extends './base.html' %}


{% block title %}New Schema{% endblock %}


{% block content %}
<!-- SCHEMA CREATE FROM -->
<div class="mt-4">
    <h3 class="mb-3">New Schema</h3>
    <form action="{% url 'schemas:create_schema' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3 float-end">
            <button id="createSchemaButton" type="submit" class="btn btn-primary">Submit</button>
        </div>
        <div>
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
        </div>
    </form>
</div>
<!-- END SCHEMA CREATE FROM -->

<!-- SCHEMA COLUMNS -->
<div id="columnRows" class="mt-4">
    <h3 class="mb-3">Schema Columns</h3>
    {% for column in columns %}
        <form class="columnRow" action="{% url 'schemas:delete_column' column.pk %}" method="POST">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col">
                    <label class="form-label">Column name</label>
                    <input type="text" class="form-control" readonly placeholder="{{ column.name }}">
                </div>
                <div class="col">
                    <label class="form-label">Type</label>
                    <input type="text" class="form-control" readonly placeholder="{{ column.type }}">
                </div>
                <div class="col {% if column.type != 'Integer' %}not-show{% endif %}">
                    <label class="form-label">From</label>
                    <input type="text" class="form-control" readonly placeholder="{{ column.start }}">
                </div>
                <div class="col {% if column.type != 'Integer' %}not-show{% endif %}">
                    <label class="form-label">To</label>
                    <input type="text" class="form-control" readonly placeholder="{{ column.end }}">
                </div>
                <div class="col-1">
                    <button type="submit" class="btn btn-danger col-submit float-end">Delete</button>
                </div>
            </div>
        </form>
    {% endfor %}
</div>
<!-- END SCHEMA COLUMNS -->

<!-- COLUMN CREATE FORM -->
<div class="mt-4 mb-5">
    <div class="border p-4 rounded-3">
        <form method="post" class="form-inline" id="createColumn">
            {% csrf_token %}
            <div class="row">
                {% for field in col_form %}
                    {% if field.label in "StartEnd" %}
                        <div class="col d-none" id="hide{{ forloop.counter }}">
                    {% else %}
                        <div class="col">
                    {% endif %}
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                {% endfor %}
            </div>
            <input type="hidden" name="schema" value="{{ schema.pk }}">
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Add column</button>
            </div>
        </form>
    </div>
</div>
<!-- END COLUMN CREATE FORM -->

{% endblock %}

schemas/templates/schemas/schema_detail.html
{% extends './base.html' %}


{% block title %}New Schema{% endblock %}


{% block content %}
<div class="mt-4">
    <h3 class="d-inline">Data Sets</h3>
    <form id="dataSetCreate" class="row float-end" action="{{ schema.get_absolute_url }}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="col-auto">
                <label for="{{ field.id_for_label }}" class="col-form-label">{{ field.label }}</label>
            </div>
            <div class="col-auto">
                {{ field }} 
            </div>
        {% endfor %}
        <div class="col-auto">
            <button id="dataSetSubmit" type="submit" class="btn btn-success">Generate data</button>
        </div>
    </form>
</div>
<table class="table table-bordered text-center mt-5">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Created</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for data_set in data_sets %}
            <tr>
                <th class="align-middle" scope="row">
                    {{ forloop.counter }}
                </th>
                <td class="align-middle">
                    {{ data_set.created|date:"Y-m-d" }}
                </td>
                <td class="align-middle">
                    {% if data_set.status == 'Processing' %}
                        <div class="btn btn-danger taskStatus">{{ data_set.status }}</div>
                    {% else %}
                        <div class="btn btn-success taskStatus">{{ data_set.status }}</div>
                    {% endif %}
                </td>
                <td>
                    <form id="getFile" action="{% url 'schemas:get_file' data_set.id %}" method="get">
                        {% if data_set.status == 'Processing' %}
                            <button class="btn btn-outline-warning disabled downloadButton" type="submit">Download</button>
                        {% else %}
                            <button class="btn btn-warning downloadButton" type="submit">Download</button>
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}